name: Continuous Delivery

on:
  push:
    tags: 'library-v*'  # push events to matching v*, i.e. v1.0, v20.15.10

env:
  PYTHON_DEFAULT_VERSION: "3.11"

jobs:
  deploy:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PDM_PUBLISH_USERNAME: __token__
      PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compute_horde
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
      - name: Install dependencies
        run: python -m pip install --upgrade nox 'pdm>=2.12,<3'
      - name: Read the Changelog
        id: read-changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.build.outputs.version }}
          path: ./compute_horde/CHANGELOG.md
      - name: Build
        run: pdm build
      - name: Create GitHub release and upload the distribution
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.build.outputs.version }}
          body: ${{ steps.read-changelog.outputs.changes }}
          draft: ${{ env.ACTIONS_STEP_DEBUG == 'true' }}
          prerelease: false
          files: ${{ steps.build.outputs.asset_path }}
      - name: Publish the package to PyPI
        run: pdm publish